version: "3.7"

services:
  kali:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: kali
    networks:
      - kali
    stdin_open: true
    tty: true
    volumes:
      - ./home:/home/external
      - ./root:/root
      - ./postgresql:/var/lib/postgresql

networks:
  kali:
    driver: bridge
